import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
//import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
// import web1 from "../public/web1.png";
// import web2 from "../public/web2.png";
// import web3 from "../public/web3.png";
// import web4 from "../public/web4.png";
// import web5 from "../public/web5.png";
// import web6 from "../public/web6.png";
import blake from "../public/blake.png";
import dms from "../public/dms.png";
import lfa from "../public/lfa.png";
import { useState } from "react";
//import Footer from "../components/Footer";
//import Link from "react-router-dom";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Blake Hoosline's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              my portfolio
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer dark:text-white text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 dark:text-white"
                  href="resume"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Blake Hoosline
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Software Engineer
            </h3>
            <p className="text-md pt-5 leading-8 text-gray-800 dark:text-white md:text-xl max-w-lg mx-auto">
              Software Engineer with a lot of passion for developing amazing and
              efficient programs!
            </p>
          </div>
          {/* <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600  dark:text-white">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div> */}
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-10 overflow-hidden md:h-96 md:w-96">
            <Image src={blake} layout="fill" objectFit="cover" />
          </div>
          <div></div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey I have developed many programs
              and wrote documentation for various full-stack programs. I've done
              work for
              <span className="text-teal-500"> freelancers </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborted with senior software engineers to create programs
              for both business and consumer usage.
            </p>
            <p className="text-md py-2 text-gray-800 dark:text-white">
              I offer a wide range of services, including full stack
              development, documentation, how to guides, and much more!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center content-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} className="w-24 h-24 content-center" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Great Usability
              </h3>
              <p className="py-2">
                Creating programs and applications that are easy to use
              </p>
              <h4 className="py-4 text-teal-800">
                Building a Frontend/UI using:
              </h4>
              <p className="text-gray-800 py-1">HTML & CSS</p>
              <p className="text-gray-800 py-1">JavaScript, jQuery, ReactJS</p>
              <p className="text-gray-800 py-1">
                NodeJS, NextJS, Tailwind CSS, etc.
              </p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark: bg-white">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Great Functionality
              </h3>
              <p className="py-2">
                Creating an application that will have many functionalities
              </p>
              <h4 className="py-4 text-teal-800">
                Building a Backend/UX using:
              </h4>
              <p className="text-gray-800 py-1">C#</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">JavaScript</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark: bg-white">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Solid Data Management
              </h3>
              <p className="py-2">
                Creating a database to hold all information neccesary
              </p>
              <h4 className="py-4 text-teal-800">Building a Database using:</h4>
              <p className="text-gray-800 py-1">Oracle</p>
              <p className="text-gray-800 py-1">Firebase</p>
              <p className="text-gray-800 py-1">Microsoft</p>
            </div>

            {/* <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your all your wants and
                needs.
              </p>
              <h4 className="py-4 text-teal-800">Tools I use</h4>
              <p className="text-gray-800 py-1">VS Code</p>
              <p className="text-gray-800 py-1">Visual Studio 2022</p>
              <p className="text-gray-800 py-1">Microsoft Stream</p>
            </div> */}
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Here is a quick glance at some of the programs that I have had a
              hand in developing or worked with in my programming journey, so
              far!
            </p>
            {/* <p className="text-md py-2 text-gray-800 dark:text-white">
              I offer a wide range of services, including programming,
              documentation, how to guides, and much more!
            </p> */}
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={dms}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={lfa}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div> */}
          </div>
        </section>
        {/* <div>
          <Footer />
        </div> */}
      </main>
    </div>
  );
}
